version: "3.9"
   
services:
  db19:
    image: postgres:14-alpine
    container_name: "db${PORT}"
    environment:
      POSTGRES_PASSWORD: "${PSQL_PASSWORD}"
      POSTGRES_DB: "${PSQL_DB}"
      POSTGRES_USER: "${PSQL_USER}"
    ports:
      - "100${PORT}:55${PORT}"
    volumes:
      - "${POSTGRES_VOLUME_PATH}:/usr/src/postgres"
    networks:
      - our-library-net
    command: "-p 55${PORT}"

  backend19:
    build:
      context: .
      dockerfile: ./Docker/back/Dockerfile
    container_name: "backend${PORT}"
    command: bash -c "python manage.py runserver 0.0.0.0:80${PORT}"
    # command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:80${PORT}"
    depends_on:
      - db19
    volumes:
      - "${DJANGO_VOLUME_PATH}:/usr/src/django/tuneful"
    ports:
      - "90${PORT}:80${PORT}"
    environment:
      PSQL_DBNAME: "${PSQL_DB}"
      PSQL_USERNAME: "${PSQL_USER}"
      PSQL_PASS: "${PSQL_PASSWORD}"
      PSQL_HOST: "db${PORT}"
      PSQL_PORT: "55${PORT}"
      JWT_TOKEN_TIME: "${JWT_TOKEN_TIME}"
    networks:
      - our-library-net
  
  frontend19:
    image: node:alpine
    build: 
      context: .
      dockerfile: ./Docker/front/Dockerfile
    container_name: "frontend19"
    command: yarn start
    depends_on:
      - backend19
    volumes:
      - "${REACT_VOLUME_PATH}:/home/frontend"
    ports:
      - "110${PORT}:60${PORT}"
    environment:
      JWT_TOKEN_TIME: "${JWT_TOKEN_TIME}"
    networks:
      - our-library-net

networks:
  our-library-net:
    external: true
    driver: bridge
