FROM node:alpine
 
WORKDIR /home/frontend
# ADD . /home/frontend

# COPY package.json package.json
# COPY package-lock.json package-lock.json
 
# RUN yarn start
 
# COPY . .
 
# CMD [ "yarn", "start" ]